/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();

        calc.add(5, 2);
        calc.subtract(10, 2);
        calc.multiply(9, 2);
        calc.divide(100, 2);

        ScientificCalculator sc = new ScientificCalculator();
        double res1 = sc.squareOf(6);
        double res2 = sc.cubeOf(3);
        double res3 = sc.powerOf(9, 2);
        double res4 = sc.squareRoot(4);
        int res5 = sc.modulo(5, 2);
        double res6 = sc.modulo_double(100, 45);

        System.out.println("squareOf =" + res1);
        System.out.println("cubeOf =" + res2);
        System.out.println("powerOff =" + res3);
        System.out.println("squareRoot =" + res4);
        System.out.println("modulo =" + res5);
        System.out.println("modulo_double =" + res6);
        



        // System.out.println(calc.getResult());
    }
}

